pipeline {
    agent any
    environment {POSTGRES_SECRET = credentials('jenkins-postgres-credentials')
        POSTGRES_SECRET_USR = "${POSTGRES_SECRET_USR}"
        POSTGRES_SECRET_PSW = "${POSTGRES_SECRET_PSW}"
    }
    stages{
        stage('Run PyTest') {
            steps {
                sh '''
                pytest tests -m "parquet_data" \
                   --db_host="postgres" \
                   --db_port="5432" \
                   --db_name="mydatabase" \
                   --db_user="$POSTGRES_SECRET_USR" \
                   --db_password="$POSTGRES_SECRET_PSW" \
                   --html=html_report/report.html
                '''
            }
        }
        stage('Archive Test Report') {
        	steps {
        	    Artifacts artifacts: 'PyTest DQ Framework/html_report/**',
    			publishHTML(target: [
        			allowMissing: false, // Fail the pipeline if the report is missing
        			keepAll: true, // Keep all reports from previous runs
        			reportDir: 'PyTest DQ Framework/html_report', // Correct directory path
        			reportFiles: 'index.html', // Entry point file reportName: 'HTML Test Report' // Display name in Jenkins
        		])
        	}
        }
    }
}